modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-v3"

[[mods]]
modId = "letmeuseit"
version = "${version}"
displayName = "LetMeUseIt"
authors = "TeamPotato"
description = '''
Disable item cooldowns if the user are in creative mode.
'''